export const LODGING_PLANNER_OVERVIEW_COPY = {
  balancedPill: "balanced",
  bedsLabel: (n: number) => `${String(n)} bed${n === 1 ? "" : "s"}`,
  demandCardTitle: "Demand",
  gapPill: (gap: number) => `gap: ${String(gap)} beds`,
  heading: "Lodging",
  headingSubtext: "both sides · capacity vs demand",
  hostsLabel: (n: number) => `${String(n)} host${n === 1 ? "" : "s"}`,
  inviteOnlyVisibility: (count: number) => `invite only (${String(count)})`,
  nonAccountMembersTitle: "Non-account members",
  publicVisibility: "public",
  sortedOwnLodgingLabel: "Sorted own lodging",
  statusHaveOwn: "Have own",
  statusNeedLodging: "Need place",
  statusNoReply: "No reply",
  statusSharing: "Share",
  supplyCardTitle: "Supply",
} as const;
