export const EXPENSE_SETTINGS_PAGE_COPY = {
  cancelButton: "Cancel",
  categoryColumnHeading: "Category",
  categoryLabelActivities: "Activities",
  categoryLabelFood: "Food",
  categoryLabelLodging: "Lodging",
  categoryLabelOther: "Other",
  categoryLabelTransport: "Transport",
  defaultParticipantsColumnHeading: "Default participants",
  errorText: "Couldn't load expense settings. Please try again.",
  headingSubtext: "Per-category defaults for this trip",
  loadingText: "Loading settings…",
  pageHeading: "Expense settings",
  pageTitle: "Expense settings",
  saveButton: "Save settings",
  unitModelColumnHeading: "Unit model",
  unitModelOptionPerUnit: "Per unit",
  unitModelOptionSharedBucket: "Shared bucket",
  unitModelOptionUsageShare: "Usage share",
} as const;
