export const EXPENSE_ENTRY_FORM_COPY = {
  amountLabel: "Amount",
  cancelButton: "Cancel",
  categoryLabel: "Category",
  categoryOptionActivities: "Activities",
  categoryOptionFood: "Food",
  categoryOptionLodging: "Lodging",
  categoryOptionOther: "Other",
  categoryOptionTransport: "Transport",
  currencyLabel: "Currency",
  descriptionLabel: "Description",
  descriptionPlaceholder: "What was this expense?",
  errorAmountInvalid: "Amount must be greater than zero",
  errorAmountRequired: "Enter an amount",
  errorPayerRequired: "Choose who paid",
  formHeading: "Add expense",
  linkedEntityLabel: "Linked to",
  linkedEntityNoneOption: "(none)",
  nonAccountCaption: "* non-account members included",
  pageTitle: "Add expense",
  participantsLabel: "Participants",
  payerLabel: "Paid by",
  payerPlaceholder: "Select a member",
  submitButton: "Save expense",
} as const;
