export const LODGING_GUEST_OVERVIEW_COPY = {
  acceptOfferAriaLabel: (host: string) => `Accept offer from ${host}`,
  acceptOfferButton: "Accept offer",
  bedsLabel: (n: number) => `${String(n)} bed${n === 1 ? "" : "s"}`,
  declineOfferAriaLabel: (host: string) => `Decline offer from ${host}`,
  declineOfferButton: "Decline",
  emptyOffersText: "No lodging offers visible for this stop yet.",
  heading: "Lodging offers",
  headingSubtext: "Offers visible to you for each stop",
  noStopsText: "No stops on this trip yet.",
  offerStatusAccepted: "Accepted",
  offerStatusDeclined: "Declined",
  offerStatusPending: "Pending",
  sortedOwnLodgingLabel: "I've sorted my own lodging for this stop",
} as const;
