export const MEMBERS_PAGE_COPY = {
  title: "Members",
  accountMembersHeading: "Account members",
  nonAccountMembersHeading: "Non-account members",
  addMemberButton: "+ Add member",
  addMemberPlaceholder: "Member name",
  addMemberSubmit: "Add",
  promoteTo: "Promote to Planner",
  removeGuest: "Remove",
  claimLinkLabel: "Copy claim link",
  proxiedBySuffix: "proxied by",
  claimPending: "claim pending",
  linkedLabel: "linked",
  rolePlanner: "Planner",
  roleGuest: "Guest",
  loadingText: "Loading members…",
  errorText: "Failed to load members.",
  emptyAccountMembers: "No account members.",
  emptyNonAccountMembers: "No non-account members.",
} as const;
