export const SCREEN_ACTIVITIES_COPY = {
  heading: "Activities",
  proposeButton: "+ Propose",
  emptyStateText: "No activities proposed yet.",
  proposalFormTitle: "Propose an Activity",
  nameLabel: "Name",
  namePlaceholder: "Activity name",
  nameRequired: "Name is required",
  durationRequired: "Duration must be at least 1 minute",
  descriptionLabel: "Description",
  descriptionPlaceholder: "Optional description",
  durationLabel: "Estimated duration (minutes)",
  timeOfDayLabel: "Time of day",
  timeOfDayTypeLabel: "Must / Preferred",
  timeOfDayTypeMust: "Must occur in",
  timeOfDayTypePreferred: "Preferred in",
  groupSizeMinLabel: "Min group size",
  groupSizeMaxLabel: "Max group size",
  costLabel: "Cost per person ($)",
  transportLabel: "Transport required",
  transportWalking: "Walking",
  transportPublicTransit: "Public transit",
  transportPrivate: "Private",
  submitButton: "Propose",
  cancelButton: "Cancel",
  votesFormat: (y: number, m: number, n: number) =>
    `Y ${String(y)} · M ${String(m)} · N ${String(n)}`,
} as const;
