import { TimeOfDaySlot } from "@/lib/types/activity";

const SLOT_LABELS: Record<TimeOfDaySlot, string> = {
  [TimeOfDaySlot.Afternoon]: "Afternoon",
  [TimeOfDaySlot.EarlyMorning]: "Early Morning",
  [TimeOfDaySlot.Evening]: "Evening",
  [TimeOfDaySlot.LateEvening]: "Late Evening",
  [TimeOfDaySlot.Morning]: "Morning",
};

export const SCREEN_ACTIVITIES_COPY = {
  activityMenuLabel: (name: string) => `Activity options for ${name}`,
  cancelButton: "Cancel",
  changeSlotOption: "Change time slot…",
  costLabel: "Cost per person ($)",
  descriptionLabel: "Description",
  descriptionPlaceholder: "Optional description",
  durationLabel: "Estimated duration (minutes)",
  durationRequired: "Duration must be at least 1 minute",
  emptyStateText: "No activities proposed yet.",
  groupSizeMaxLabel: "Max group size",
  groupSizeMinLabel: "Min group size",
  heading: "Activities",
  nameLabel: "Name",
  namePlaceholder: "Activity name",
  nameRequired: "Name is required",
  pinnedPrefix: "📌",
  pinOption: "Pin (required)",
  pinToSlotOption: "Pin to time slot…",
  proposalFormTitle: "Propose an Activity",
  proposeButton: "+ Propose",
  slotLabel: (slot: TimeOfDaySlot) => SLOT_LABELS[slot],
  submitButton: "Propose",
  timeOfDayLabel: "Time of day",
  timeOfDayTypeLabel: "Must / Preferred",
  timeOfDayTypeMust: "Must occur in",
  timeOfDayTypePreferred: "Preferred in",
  transportLabel: "Transport required",
  transportPrivate: "Private",
  transportPublicTransit: "Public transit",
  transportWalking: "Walking",
  unpinOption: "Unpin",
  votesFormat: (y: number, m: number, n: number) =>
    `Y ${String(y)} · M ${String(m)} · N ${String(n)}`,
} as const;
