export const TRIP_STRUCTURE_COPY = {
  heading: "Trip structure",
  pageTitle: "Plan structure",
  headingSubtext: "stops & legs",
  addStop: "+ Stop",
  addLeg: "+ Add leg",
  editStop: "Edit",
  saveStop: "Save",
  cancelEdit: "Cancel",
  stopLabel: (n: number) => "STOP " + String(n),
  nameLabel: "Name",
  startDateLabel: "Start date",
  endDateLabel: "End date",
  errorNameRequired: "Name is required",
  errorStartDateRequired: "Start date is required",
  errorEndDateRequired: "End date is required",
  errorEndBeforeStart: "End date must be on or after start date",
  submitAddStop: "Add stop",
} as const;
