export const EXPENSES_LIST_PAGE_COPY = {
  addExpenseButton: "Add expense",
  categoryLabel: "Category:",
  emptyText: "No expenses logged yet.",
  errorText: "Couldn't load expenses. Please try again.",
  heading: "Expenses",
  headingSubtext: "Per-trip expense log",
  linkedEntityLabel: "For:",
  loadingText: "Loading expenses…",
  pageTitle: "Expenses",
  payerLabel: "Paid by",
  preFillActivityRsvpLabel: "Activity RSVP",
  preFillHeading: "Quick-add",
  preFillLodgingUnitLabel: "Lodging unit",
  preFillStopAttendanceLabel: "Stop attendance",
  preFillTransportLegLabel: "Transport leg",
} as const;
