export const TRIP_DASHBOARD_COPY = {
  appTitle: "Trip Planner",
  openMenuAriaLabel: "Open menu",
  notificationsAriaLabel: "Notifications",
  quickAccessHeading: "Quick Access",
  quickAccessCalendar: "Calendar",
  quickAccessDestinations: "Destinations",
  quickAccessNotifications: "Notifications",
  quickAccessTrips: "Trips",
  activeTripsHeading: "Active",
  pastTripsHeading: "Past",
  phasePlanning: "Planning",
  phaseCoordination: "Coordination",
  phaseSettlingUp: "Settling Up",
  phaseSettled: "Settled",
} as const;
