export const APP_DRAWER_COPY = {
  allTrips: "← All trips",
  appName: "Trip Planner",
  navActivities: "Activities",
  navArchive: "Archive",
  navAvailability: "Availability",
  navBalances: "Balances",
  navCalendar: "Calendar",
  navCandidatePlaces: "Candidate places",
  navDestinations: "Destinations",
  navExpenses: "Expenses",
  navLodging: "Lodging",
  navMembers: "Members",
  navNotifications: "Notifications",
  navPlanStructure: "Plan structure",
  navSettings: "Settings",
  navTransportation: "Transportation",
  navTripOverview: "Trip overview",
  navTrips: "Trips",
  recentTripsSectionHeading: "Recent trips",
  signOut: "Sign out",
  switchSectionHeading: "Switch",
  tripSectionHeading: "This trip",
  userSectionHeading: "You",
} as const;
